start
:鶏の手羽元に塩をモミ込む;
:保存袋にA（下味材料）と鶏手羽元を入れる;
fork
    :鶏手羽元を冷蔵庫に入れて\n一時間待つ;
        note right
            <b><u>【Memo】
            鶏手羽元にAを
            なじませるため    
        end note


' Forkされた二つ目の処理
fork again
    :B（スパイス群）を\n合わせて混ぜる;
    :玉ねぎをみじん切りにする;
fork again
    :ご飯を炊く;
end fork
:フライパンを用意する;
    note left
        <b><u>【Memo】
        以降の手順は
        フライパン上で行う
    end note
:クミンシードと玉ねぎを炒める;
    note right
        <b><u>【Memo】
        可能であれば
        オリーブオイルを使う
    end note
:玉ねぎがやや色づいてきたら、トマト缶の中身を投入する;
:トマト缶の半分の分量の水を加える;
:A（下味材料）に漬け込んでおいた鶏手羽元と\nB（スパイス群）を投入する;
:20分ほど弱火で煮込む;
:火を止め、ガラムマサラを加える;
:ご飯と合わせて、出来上がり！;
stop

@enduml
